%% Vertical and Horizontal Position
figure('Units', 'pixels', ...
   'Position', [300 300 640 480]);
subplot(211)
plot(timelqg(:,1),avgstateslqg(:,9),':');grid on;
xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,'FontSize'   , 12                    );
ylabel('Vertical Position (cm)', 'FontName'   , 'Times New Roman' ,'FontSize'   , 12                      );
legend('Measured Response')
subplot(2,1,2);
state1  = plot(timelqg(:,1),avgstateslqg(:,1),'-',timelqg(:,1),avgstateslqg(:,5),'--');
grid on;
set(state1,'LineWidth'       , 3          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Vertical Position (cm)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );
set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);
legend('Actual Response','Estimated Response')


figure('Units', 'pixels', ...
   'Position', [300 300 640 480]);
subplot(211)
plot(timelqg(:,1),avgstateslqg(:,20),':');grid on;
xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,'FontSize'   , 12                    );
ylabel('Horizontal Position (cm)', 'FontName'   , 'Times New Roman' ,'FontSize'   , 12                      );
legend('Measured Response')
subplot(2,1,2);
state1  = plot(timelqg(:,1),avgstateslqg(:,12),'-',timelqg(:,1),avgstateslqg(:,16),'--');
grid on;
set(state1,'LineWidth'       , 3          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Horizontal Position (cm)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );
set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);
legend('Actual Response','Estimated Response')

%% Pointing Error
rmse1 = norm(avgstateslqg(:,6))/sqrt(length(avgstateslqg(:,6)));
figure('Units', 'pixels', ...
   'Position', [300 300 640 480]);
subplot(2,1,1);
error1  = plot(timelqg(:,1),avgstateslqg(:,6));
grid on;
set(error1               , ...
  'LineStyle'       , '--'        , ...
  'Color'           , 'r'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Vertical Poiting Error (cm)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );
hTitle = title(['RMSE = ' num2str(rmse1)], 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );
set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);

rmse2 = norm(avgstateslqg(:,12))/sqrt(length(avgstateslqg(:,12)));
subplot(2,1,2);
error2  = plot(timelqg(:,1),avgstateslqg(:,12));
grid on;
set(error2               , ...
  'LineStyle'       , '-'        , ...
  'Color'           , 'bl'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Horizontal Poiting Error (cm)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );
hTitle = title(['RMSE = ' num2str(rmse2)], 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );
set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);
%% VELOCITY

figure('Units', 'pixels', ...
   'Position', [300 300 640 480]);
subplot(2,1,1);
state2  = plot(timelqg(:,1),avgstateslqg(:,2));
grid on;
set(state2                , ...
  'LineStyle'       , '--'        , ...
  'Color'           , 'r'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('\omega_{ey} (rad per sec)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );
set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);

subplot(2,1,2);
state6  = plot(timelqg(:,1),avgstateslqg(:,8));
grid on;
set(state6                , ...
  'LineStyle'       , '-'        , ...
  'Color'           , 'b'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('\omega_{ez} (rad per sec)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );


set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);


%% CURRENT
figure('Units', 'pixels', ...
   'Position', [300 300 640 480]);
subplot(2,1,1);
state3  = plot(timelqg(:,1),avgstateslqg(:,3));
grid on;
set(state3                , ...
  'LineStyle'       , '--'        , ...
  'Color'           , 'r'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Pitch Current (A)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );


set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);

subplot(2,1,2);
state7  = plot(timelqg(:,1),avgstateslqg(:,9));
grid on;
set(state7                , ...
  'LineStyle'       , '-'        , ...
  'Color'           , 'b'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Yaw Current (A)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );


set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);

%% CURRENT COMMAND

figure('Units', 'pixels', ...
   'Position', [300 300 640 480]);
subplot(2,1,1);
state4  = plot(timelqg(:,1),avgstateslqg(:,4));
grid on;
set(state4               , ...
  'LineStyle'       , '--'        , ...
  'Color'           , 'r'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Pitch motor current command i_{aEL}^* (A)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );


set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);

subplot(2,1,2);
state4  = plot(timelqg(:,1),avgstateslqg(:,10));
grid on;
set(state4               , ...
  'LineStyle'       , '-'        , ...
  'Color'           , 'b'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Yaw motor current command i_{aAZ}^* (A)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );


set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);
%% CONTROL Speed COMMAND

figure('Units', 'pixels', ...
   'Position', [300 300 640 480]);
subplot(2,1,1);
control1  = plot(timelqg(:,1),avgstateslqg(:,5));
grid on;
set(control1               , ...
  'LineStyle'       , '--'        , ...
  'Color'           , 'r'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Pitch Speed Control Command \omega_{EL}^* (V)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );


set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);

subplot(2,1,2);
control2  = plot(timelqg(:,1),avgstateslqg(:,11));
grid on;
set(state4               , ...
  'LineStyle'       , '-'        , ...
  'Color'           , 'b'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Yaw Speed Control Command \oemga_{AZ}^* (V)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );


set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);
