%% Vertical and Horizontal Position
figure('Units', 'pixels', ...
   'Position', [300 300 640 480]);
state1  = plot(timelqg(:,1),vertrepeat{19});
grid on;
set(state1                , ...
  'LineStyle'       , '--'        , ...
  'Color'           , 'r'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Vertical Position (cm)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );
set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);

figure('Units', 'pixels', ...
   'Position', [300 300 640 480]);
state2  = plot(timelqg(:,1),horzrepeat{19});
grid on;
set(state2                , ...
  'LineStyle'       , '-'        , ...
  'Color'           , 'bl'        , ...
  'LineWidth'       , 2          );

hXLabel = xlabel('Time (second)' , 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                    );
hYLabel = ylabel('Horizontal Position (cm)', 'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12                      );
set(gca, ...
  'FontName'   , 'Times New Roman' ,...
  'FontSize'   , 12);